# Generated by Django 3.1.1 on 2020-10-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200918_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Opção', 'verbose_name_plural': 'Opções'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
        migrations.AddField(
            model_name='question',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
